// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVONb1v3pr3PkOIy3RKm-Sg9B9ZwMXAls',
    appId: '1:1067053335733:android:560735996a6e867d0d2afc',
    messagingSenderId: '1067053335733',
    projectId: 'ogs-dev-project',
    storageBucket: 'ogs-dev-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwB1sdYaCkNN9dGtNEWzSCF_atR4Jj59Y',
    appId: '1:1067053335733:ios:b53f4d632c55742a0d2afc',
    messagingSenderId: '1067053335733',
    projectId: 'ogs-dev-project',
    storageBucket: 'ogs-dev-project.firebasestorage.app',
    iosBundleId: 'com.ogs.app.ogs',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCScMUTCzpiYkdMnN4FAgYulyWLvu1ghWY',
    appId: '1:1067053335733:web:05a59c1cb86b12050d2afc',
    messagingSenderId: '1067053335733',
    projectId: 'ogs-dev-project',
    authDomain: 'ogs-dev-project.firebaseapp.com',
    storageBucket: 'ogs-dev-project.firebasestorage.app',
    measurementId: 'G-958P40M3KC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwB1sdYaCkNN9dGtNEWzSCF_atR4Jj59Y',
    appId: '1:1067053335733:ios:56f269cbd44ffb750d2afc',
    messagingSenderId: '1067053335733',
    projectId: 'ogs-dev-project',
    storageBucket: 'ogs-dev-project.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCScMUTCzpiYkdMnN4FAgYulyWLvu1ghWY',
    appId: '1:1067053335733:web:6eaf574af29f129a0d2afc',
    messagingSenderId: '1067053335733',
    projectId: 'ogs-dev-project',
    authDomain: 'ogs-dev-project.firebaseapp.com',
    storageBucket: 'ogs-dev-project.firebasestorage.app',
    measurementId: 'G-XKHEKH5TQD',
  );

}